<?php
/**
 * @see Mage_Checkout_Block_Agreements
 */
?>

<form action="" id="checkout-agreements" onsubmit="return false;">
  <ol class="checkout-agreements">
    <div>
        <label for="checkout-comments">
            <?php echo Mage::helper('core')->__("Enter additional comments here") ?>
            <small><?php echo("e.g 'If no one is home please ring or leave nextdoor'") ?></small>
        </label>
        <textarea name="checkoutcomments" id="checkoutcomments" style="width: 100%; height: 100px;"></textarea>
    </div>

<?php if ($this->getAgreements()) : ?>

        <?php foreach ($this->getAgreements() as $_a): ?>
            <li>
                <div class="agreement-content"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
                    <?php if ($_a->getIsHtml()):?>
                        <?php echo $_a->getContent() ?>
                    <?php else:?>
                        <?php echo nl2br($this->escapeHtml($_a->getContent())) ?>
                    <?php endif; ?>
                </div>
                <p class="agree">
                    <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->escapeHtml($_a->getCheckboxText()) ?>" class="checkbox" /><label for="agreement-<?php echo $_a->getId()?>"><?php echo $_a->getIsHtml() ? $_a->getCheckboxText() : $this->escapeHtml($_a->getCheckboxText()) ?></label>
                </p>
            </li>
        <?php endforeach ?>

<?php endif; ?>
    </ol>
</form>
